import type { IRNode } from '../core/types.js';
import { classNameOf } from '../core/naming.js';
import type { StyleFlavor } from './types.js';

const ORDER = [
  'display', 'position', 'top', 'right', 'bottom', 'left', 'z-index',
  'flex-direction', 'flex-wrap', 'flex-grow', 'flex-shrink', 'flex-basis',
  'align-items', 'align-self', 'justify-content', 'gap', 'row-gap', 'column-gap',
  'grid-template-columns', 'grid-template-rows',
  'box-sizing', 'width', 'height', 'min-width', 'max-width', 'min-height', 'max-height',
  'margin', 'padding', 'overflow', 'object-fit', 'aspect-ratio',
  'font-family', 'font-size', 'font-weight', 'font-style', 'line-height',
  'letter-spacing', 'text-align', 'text-transform', 'text-decoration', 'color',
  'background', 'background-color', 'background-image', 'background-size',
  'background-position', 'background-repeat',
  'border', 'border-radius', 'box-shadow', 'outline', 'opacity',
  'transition', 'transform', 'filter', 'backdrop-filter', 'cursor', 'white-space',
];

function mergeShorthands(styles: Record<string, string>): Record<string, string> {
  const s = { ...styles };
  for (const prop of ['padding', 'margin'] as const) {
    const t = s[`${prop}-top`], r = s[`${prop}-right`], b = s[`${prop}-bottom`], l = s[`${prop}-left`];
    if (t !== undefined && r !== undefined && b !== undefined && l !== undefined) {
      s[prop] = collapseBox(t, r, b, l);
      for (const side of ['top', 'right', 'bottom', 'left']) delete s[`${prop}-${side}`];
    }
  }
  if (s['background-color'] && s['background-image']) {
    s['background'] = `${s['background-image']} ${s['background-color']}`;
    delete s['background-color'];
    delete s['background-image'];
  }
  return s;
}

function collapseBox(t: string, r: string, b: string, l: string): string {
  if (t === r && r === b && b === l) return t;
  if (t === b && r === l) return `${t} ${r}`;
  if (r === l) return `${t} ${r} ${b}`;
  return `${t} ${r} ${b} ${l}`;
}

export function cssDeclarations(node: IRNode): string[] {
  const merged = mergeShorthands(node.styles);
  const lines: string[] = [];
  for (const prop of ORDER) {
    const value = merged[prop];
    if (value) lines.push(`  ${prop}: ${value};`);
  }
  for (const [prop, value] of Object.entries(merged)) {
    if (!ORDER.includes(prop) && value) lines.push(`  ${prop}: ${value};`);
  }
  return lines;
}

export function generateCss(root: IRNode, flavor: StyleFlavor): string {
  if (flavor === 'tailwind') return '';
  const blocks: string[] = [];
  const stack = [root];
  while (stack.length) {
    const node = stack.pop()!;
    const cls = classNameOf(node);
    if (cls) {
      const decls = cssDeclarations(node);
      if (decls.length) blocks.push(`.${cls} {\n${decls.join('\n')}\n}`);
    }
    for (let i = node.children.length - 1; i >= 0; i--) stack.push(node.children[i]);
  }
  return `/* Generated by SnapUI */\n` + blocks.join('\n\n') + '\n';
}
