import { test } from 'node:test';
import assert from 'node:assert/strict';
import { assignClassNames, classNameOf, kebab, pascal } from '@snapui/core';
import { generate, generateCss, tailwindClasses } from '@snapui/generators';

const sampleTree = () => ({
  tag: 'section',
  attrs: {},
  styles: { display: 'flex', 'flex-direction': 'column', gap: '16px', padding: '40px', color: 'rgb(255, 255, 255)', 'background-color': 'rgb(17, 17, 17)', 'border-radius': '12px' },
  children: [
    { tag: 'h1', attrs: {}, text: 'Financial infrastructure', styles: { 'font-size': '56px', 'font-weight': '700', color: 'rgb(255, 255, 255)' }, children: [] },
    { tag: 'p', attrs: {}, text: 'Millions of companies.', styles: { 'font-size': '18px', 'line-height': '28px', color: 'rgb(160, 160, 174)' }, children: [] },
    { tag: 'a', attrs: { href: '/start' }, text: 'Start now', styles: { display: 'inline-block', padding: '8px 16px', 'background-color': 'rgb(99, 91, 255)' }, children: [] },
  ],
});

test('naming: kebab and pascal helpers', () => {
  assert.equal(kebab('HeroSection'), 'hero-section');
  assert.equal(pascal('hero-section'), 'HeroSection');
});

test('naming: unique BEM-ish class assignment', () => {
  const root = sampleTree();
  assignClassNames(root, 'HeroSection');
  assert.equal(classNameOf(root), 'hero-section');
  const classes = ['hero-section__h1', 'hero-section__p', 'hero-section__a'];
  for (const child of root.children) {
    assert.ok(classes.includes(classNameOf(child)), `expected ${classNameOf(child)}`);
  }
});

test('css: emits only non-default styles, ordered', () => {
  const root = sampleTree();
  assignClassNames(root, 'HeroSection');
  const css = generateCss(root, 'css');
  assert.ok(css.includes('.hero-section {'));
  assert.ok(css.includes('display: flex;'));
  assert.ok(css.includes('padding: 40px;'));
  assert.ok(css.includes('/* Generated by SnapUI */'));
});

test('tailwind: maps common declarations', () => {
  const node = sampleTree();
  const tw = tailwindClasses(node);
  assert.ok(tw.includes('flex'), `got ${tw}`);
  assert.ok(tw.includes('flex-col'), `got ${tw}`);
  assert.ok(tw.includes('gap-4'), `got ${tw}`);
  assert.ok(tw.includes('p-10'), `got ${tw}`);
  assert.ok(tw.includes('text-white'), `got ${tw}`);
  assert.ok(tw.includes('rounded-xl'), `got ${tw}`);
});

test('react: generates TSX + CSS + stories', () => {
  const root = sampleTree();
  assignClassNames(root, 'HeroSection');
  const files = generate({ componentName: 'HeroSection', framework: 'react', style: 'css', root });
  const paths = files.map((f) => f.path);
  assert.deepEqual(paths, [
    'components/HeroSection.tsx',
    'styles/hero-section.css',
    'storybook/HeroSection.stories.tsx',
  ]);
  const tsx = files[0].content;
  assert.ok(tsx.includes('export interface HeroSectionProps'));
  assert.ok(tsx.includes("import './HeroSection.css';"));
  assert.ok(tsx.includes('Financial infrastructure'));
  assert.ok(tsx.includes('<a className="hero-section__a" href="/start">'));
});

test('react: tailwind mode embeds utilities, no css file', () => {
  const root = sampleTree();
  assignClassNames(root, 'Hero');
  const files = generate({ componentName: 'Hero', framework: 'react', style: 'tailwind', root });
  assert.equal(files.filter((f) => f.path.endsWith('.css')).length, 0);
  assert.ok(files[0].content.includes('className={["'));
  assert.ok(files[0].content.includes('flex'));
});

test('react: modules mode uses styles map', () => {
  const root = sampleTree();
  assignClassNames(root, 'Card');
  const files = generate({ componentName: 'Card', framework: 'react', style: 'modules', root });
  assert.ok(files[0].content.includes('styles['));
  assert.ok(files[1].path.endsWith('.module.css'));
});

test('vue: generates SFC with template + css import', () => {
  const root = sampleTree();
  assignClassNames(root, 'Pricing');
  const files = generate({ componentName: 'Pricing', framework: 'vue', style: 'css', root });
  assert.equal(files[0].path, 'components/Pricing.vue');
  assert.ok(files[0].content.includes('<script setup lang="ts">'));
  assert.ok(files[0].content.includes("<template>"));
  assert.ok(files[0].content.includes("import '../styles/pricing.css';"));
});

test('svelte + html: generate files', () => {
  const root = sampleTree();
  assignClassNames(root, 'Nav');
  const svelte = generate({ componentName: 'Nav', framework: 'svelte', style: 'css', root });
  assert.ok(svelte[0].path.endsWith('.svelte'));
  const html = generate({ componentName: 'Nav', framework: 'html', style: 'tailwind', root });
  assert.ok(html[0].path.endsWith('.html'));
});

test('void elements render self-closed', () => {
  const root = {
    tag: 'div', attrs: {}, styles: {}, children: [
      { tag: 'img', attrs: { src: 'https://example.com/a.png', alt: 'A' }, styles: { width: '100px' }, children: [] },
    ],
  };
  assignClassNames(root, 'Img');
  const files = generate({ componentName: 'Img', framework: 'react', style: 'css', root });
  assert.ok(files[0].content.includes('<img className="img__img" src="https://example.com/a.png" alt="A" />'));
});

test('html escapes text and attributes', () => {
  const root = {
    tag: 'div', attrs: {}, styles: {}, text: '<script>alert(1)</script>', children: [],
  };
  assignClassNames(root, 'Safe');
  const files = generate({ componentName: 'Safe', framework: 'html', style: 'css', root });
  assert.ok(!files[0].content.includes('<script>alert'));
  assert.ok(files[0].content.includes('&lt;script&gt;'));
});
